# Generated by Django 3.2.12 on 2022-07-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=30, verbose_name='Tile')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('publisher', models.CharField(max_length=255, verbose_name='Publisher')),
            ],
        ),
    ]
